star_id_store:
    resource: "@StarIdStoreBundle/Controller/"
    type:     annotation
    prefix:   /


star_id_user:
    resource: "@StarIdUserBundle/Resources/config/routing.yml"

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
    
login:
    pattern:   /login
    defaults:  { _controller: StarIdUserBundle:Security:login }

login_check:
    pattern:   /login_check

logout:
    pattern:   /logout    
    
 